"""
Regenerate command for doc-evergreen.

Regenerates documentation when source files have been updated.
"""

import hashlib
import json
from pathlib import Path

import click

from doc_evergreen.core.project import get_project_dir


def get_file_content_hash(file_path: str, repo_path: Path) -> str | None:
    """
    Get the SHA-256 hash of a file's content.

    Args:
        file_path: Path to file (relative to repo root)
        repo_path: Path to repository root

    Returns:
        SHA-256 hash string or None if file doesn't exist
    """
    full_path = repo_path / file_path
    if not full_path.exists():
        return None

    try:
        with open(full_path, "rb") as f:
            content = f.read()
            return hashlib.sha256(content).hexdigest()
    except Exception:
        return None


def check_if_previously_generated(doc_path: str, repo_path: Path) -> bool:
    """
    Check if a document has been previously generated by the system.

    Args:
        doc_path: Path to document (relative to repo root)
        repo_path: Path to repository root

    Returns:
        True if document has previous generation metadata, False otherwise
    """
    project_dir = get_project_dir(doc_path, repo_path)
    generated_metadata_path = project_dir / "5_generated_doc" / "metadata.json"

    if not generated_metadata_path.exists():
        return False

    try:
        with open(generated_metadata_path, encoding="utf-8") as f:
            metadata = json.load(f)
            return "versions" in metadata and len(metadata["versions"]) > 0
    except (json.JSONDecodeError, KeyError):
        return False


def get_last_generation_info(doc_path: str, repo_path: Path) -> dict | None:
    """
    Get the last generation information for a document.

    Args:
        doc_path: Path to document (relative to repo root)
        repo_path: Path to repository root

    Returns:
        Dictionary with last generation info or None if not found
    """
    project_dir = get_project_dir(doc_path, repo_path)
    generated_metadata_path = project_dir / "5_generated_doc" / "metadata.json"

    if not generated_metadata_path.exists():
        return None

    try:
        with open(generated_metadata_path, encoding="utf-8") as f:
            metadata = json.load(f)
            versions = metadata.get("versions", [])
            if not versions:
                return None

            # Get the most recent version
            latest_version = versions[-1]
            inputs = latest_version.get("inputs", {})
            source_files_data = inputs.get("source_files_content", [])

            # Extract source files and compute current content hashes
            source_files_with_hashes = {}
            for file_info in source_files_data:
                if isinstance(file_info, dict):
                    file_path = file_info.get("file_path", "")
                    if file_path:
                        # Get stored hash if it exists, otherwise compute from current content
                        stored_hash = file_info.get("content_hash")
                        if not stored_hash:
                            # Legacy: compute hash from stored content or current file
                            stored_hash = "legacy-no-hash"
                        source_files_with_hashes[file_path] = stored_hash

            return {
                "timestamp": latest_version.get("version", "unknown"),
                "about": inputs.get("doc_description", ""),
                "source_patterns": [],  # Not stored in metadata
                "source_files": source_files_with_hashes,
                "template_version": inputs.get("customized_template", {}).get("version", "unknown"),
            }
    except (json.JSONDecodeError, KeyError):
        return None


def check_source_files_updated(last_generation: dict, repo_path: Path) -> tuple[bool, list[str]]:
    """
    Check if any source files have been updated since last generation.

    Args:
        last_generation: Dictionary containing last generation metadata
        repo_path: Path to repository root

    Returns:
        Tuple of (any_updated, list_of_updated_files)
    """
    source_files = last_generation.get("source_files", {})
    updated_files = []

    for file_path, old_content_hash in source_files.items():
        current_content_hash = get_file_content_hash(file_path, repo_path)

        # File updated if content hash changed (or file doesn't exist)
        if current_content_hash is None:
            # File no longer exists - treat as updated so user gets notified
            updated_files.append(file_path)
        elif current_content_hash != old_content_hash:
            # Content changed
            updated_files.append(file_path)

    return (len(updated_files) > 0, updated_files)


def execute_regenerate(doc_path: str) -> None:
    """
    Execute regenerate command for a document.

    Smart cascading regeneration:
    1. Identify which source files have content changes
    2. Regenerate summaries ONLY for changed files (Step 2)
    3. Regenerate relevancy scores ONLY for changed files (Step 3)
    4. Regenerate template with all files using latest summaries/relevancy (Step 4)
    5. Generate final document (Step 5)

    Args:
        doc_path: Path to document to regenerate (relative to repo root)

    Raises:
        click.ClickException: If document not previously generated or regeneration fails
    """
    # Get repo root
    repo_path = Path.cwd()

    # Step 1: Check if document was previously generated
    if not check_if_previously_generated(doc_path, repo_path):
        raise click.ClickException(
            f"Document '{doc_path}' has not been previously generated by doc-evergreen.\n"
            f"Use the 'create' command instead:\n"
            f"  doc-evergreen create --about '<description>' --output '{doc_path}'"
        )

    click.echo(f"📄 Checking regeneration status for: {doc_path}")
    click.echo("")

    # Get last generation info
    last_generation = get_last_generation_info(doc_path, repo_path)
    if not last_generation:
        raise click.ClickException(f"Could not load generation metadata for '{doc_path}'")

    click.echo("✅ Found previous generation metadata")
    click.echo(f"   Last generated: {last_generation.get('timestamp', 'unknown')}")
    click.echo(f"   About: {last_generation.get('about', 'unknown')}")
    click.echo("")

    # Show source files used
    source_files = last_generation.get("source_files", {})
    click.echo(f"📂 Source files used ({len(source_files)} total):")
    for file_path in sorted(source_files.keys()):
        click.echo(f"   - {file_path}")
    click.echo("")

    # Check if source files have been updated
    any_updated, updated_files = check_source_files_updated(last_generation, repo_path)

    if not any_updated:
        click.echo("✅ No source files have been updated since last generation")
        click.echo("   Document is up to date - no regeneration needed")
        return

    click.echo(f"🔄 Found {len(updated_files)} updated source file(s):")
    for file_path in updated_files:
        click.echo(f"   - {file_path}")
    click.echo("")

    # Now do smart cascading regeneration
    click.echo("♻️  Starting smart regeneration (only updating what changed)...")
    click.echo("")

    # Import create command utilities
    from doc_evergreen.commands.create import execute_create

    # Get about description
    about = last_generation.get("about", "")

    # Convert source files dict to list of file paths
    all_source_files = list(source_files.keys())

    # Call create command starting from step 2 (skip discovery since we know the files)
    # The create command will handle:
    # - Step 2: Regenerating summaries (will use cache for unchanged files)
    # - Step 3: Regenerating relevancy (will use cache for unchanged files)
    # - Step 4: Creating new customized template with all files
    # - Step 5: Generating final document

    try:
        # Use start_step=2 to skip file discovery and use our known file list
        execute_create(
            about=about,
            output=Path(doc_path),
            sources=all_source_files,  # Pass exact list of files previously used
            start_step=2,  # Skip discovery, start at summarization
        )
    except Exception as e:
        raise click.ClickException(f"Regeneration failed: {e}")
